import {
  Wrench,
  Globe,
  Target,
  Users,
  Package,
  HardDrive,
  Circle,
  Compass,
  GraduationCap,
  Brain,
  ArrowRight,
  Rocket,
  Sparkles,
  Zap,
  Handshake,
  ChevronRight,
  Code,
  Database,
  Server,
  Laptop,
  Cpu,
  Layers,
  GitBranch,
  Terminal,
  Cloud,
  Shield,
  Award,
  TrendingUp,
  Briefcase,
  Building2,
  Mail,
  Phone,
  MapPin,
  ExternalLink,
  Check,
  Star,
  Heart,
  MessageCircle,
  Calendar,
  Clock,
  FileText,
  Settings,
  Search,
  Plus,
  Trash2,
  Edit3,
  Save,
  Download,
  Upload,
  RefreshCw,
  Bell,
  User,
  LogOut,
  LogIn,
  Home,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  X,
  Menu,
  Eye,
  Lock,
  Wifi,
  Sun,
  Moon,
  Monitor,
  Play,
  Pause,
  Volume2,
  Map,
  Flag,
  Anchor,
  Activity,
  Flame,
  Droplet,
  Leaf,
  Recycle,
  Power,
  Battery,
  Sliders,
  ToggleRight,
} from 'lucide-react';

const iconMap = {
  Wrench, Globe, Target, Users, Package,
  HardDrives: HardDrive,
  Compass,
  Student: GraduationCap,
  Brain,
  ArrowRight,
  RocketLaunch: Rocket,
  Sparkle: Sparkles,
  Lightning: Zap,
  Handshake,
  ChevronRight,
  Code, Database, Server, Laptop, Cpu, Layers, GitBranch, Terminal, Cloud,
  Shield, Award, TrendingUp, Briefcase, Building2,
  Mail, Phone, MapPin, ExternalLink,
  Check, Star, Heart, MessageCircle,
  Calendar, Clock, FileText, Settings, Search,
  Plus, Trash2, Edit3, Save, Download, Upload,
  RefreshCw, Bell, User, LogOut, LogIn, Home,
  ArrowLeft, ArrowUp, ArrowDown, X, Menu,
  Eye, Lock, Wifi, Sun, Moon, Monitor,
  Play, Pause, Volume2,
  Map, Flag, Anchor,
  Activity, Flame, Droplet, Leaf, Recycle,
  Power, Battery,
  Tool: Wrench,
  Sliders, ToggleRight,
  Circle,
};

export function Icon({ name, size = 24, color = 'currentColor', className, strokeWidth: sw = 2, weight, ...props }) {
  let strokeWidth = sw;
  if (weight === 'bold') strokeWidth = 2.5;
  if (weight === 'duotone') strokeWidth = 1.5;
  if (weight === 'thin') strokeWidth = 1;

  const LucideIcon = iconMap[name] || Circle;

  return (
    <LucideIcon
      size={size}
      color={color}
      strokeWidth={strokeWidth}
      className={className}
      {...props}
    />
  );
}